### ISSUE TITLE
The app does have the FIIL Key pro

### ISSUE THREAD

**Issue by OwadAlee** [Kiwironic/FIILEng#1]
Hello, I bought a FIIL Key Pro and I can't find it in FIIl+ nor your app. Any idea if it will be added soon ? 
Thanks in advance

**Comment by VuDucVN** [comment]
Yeah, pls can you make a translation for FIIL Key Pro

**Comment by Kiwironic** [comment]
I would love to do that, but I don't have that model to test. I must have the model to test it on. If you like to donate one or send me a sample. I would do it in 2 days.

**Comment by VuDucVN** [comment]
While I cant send u a sample from Vietnam, Im eager to be a tester once it's ready. Let me know how I can assist. U just make a translation for that and ill test it. Appreciate your effort!

**Comment by Kiwironic** [comment]
I wish it was that easy man. Most of the text is written encoded, I cannot simply search in files and translate. I have to find the right text first, then encode it then find the encoded text in some of the files, then decode them, translate them, then change the file :) 
That's why I need a device to test as the app behaves differently based on each device connected.

**Comment by Kiwironic** [comment]
I wish it was that easy man. Most of the text is written encoded, I cannot simply search in files and translate. I have to find the right text first, then encode it then find the encoded text in some of the files, then decode them, translate them, then change the file :)
That's why I need a device to test as the app behaves differently based on each device connected.

**Comment by VuDucVN** [comment]
So there's no way to translate this app ?

**Comment by VuDucVN** [comment]
I hope this message finds you well. I am writing to request your
collaboration in completing a project that aligns with the functionalities
of FIIL+ translated application. I actually do some research and find how
to decompile and compile the app. I have translated almost all the text in
the FIIL Key Pro configuration, compile, sign and when i tested it, it
works flawlessly. But there are some of the text i can't translate it since
i don't find it appearance on the xml files. Therefore, I kindly request
your assistance in completing the rest of the xml translation and
integrating my project with your FIIL+ app. I can give u my FIIL+ app that
have been modified.

Vào Th 3, 13 thg 2, 2024 vào lúc 08:29 MB ***@***.***> đã
viết:

**Comment by Kiwironic** [comment]
Hello my friend, 

You are doing a good job, but the problem is that the app doesn't use XML files. Most of the text is found in the code and also written encoded, so you must find it first, then decode it back to Chinese, translate it and put it back. 

They are all over the code, I use a find in files, then try to find them to decode them, translate and so on. You are on the right path. 

Don't forget to translate the images, that's usually the easy part.

**Comment by Kiwironic** [comment]
Here are some examples: 

![image](https://github.com/Kiwironic/FIILEng/assets/6486759/cd5c94cb-c651-4bba-8dd3-438386a3d17f)

`const-string v1, "\u5927\u5267\u9662" `

The unicode will translate to:  大剧院
![image](https://github.com/Kiwironic/FIILEng/assets/6486759/18089fcf-e6a7-41cf-b727-eba174629286)

Then you need to translate it to English: 
![image](https://github.com/Kiwironic/FIILEng/assets/6486759/1eabc990-3a64-4e30-841d-c8e896dfda4c)

Grand Theater which seems like an equaliser setting. 

Replace the 
`const-string v1, "\u5927\u5267\u9662" `

With 

`const-string v1, "Big Theatre" `

And keep going

**Comment by Kiwironic** [comment]
You must keep doing that for the whole app, which is a very time-consuming task, and no guarantees until you test it on the actual product. 

You can use a project explorer and search for "/.u" this will show you all the unicode strings in all files. There are so so many, in the 100,000s of strings to translate :)

**Comment by Kiwironic** [comment]
Many many files and many many strings. 

Even after I did the correct translation and testing, in the code you will find many untranslated strings:

![image](https://github.com/Kiwironic/FIILEng/assets/6486759/1915eaa9-27cf-4cc8-b567-7d7b7928c6e7)

Here are mainly the paths you want to look into:
![image](https://github.com/Kiwironic/FIILEng/assets/6486759/1afc9f7f-9866-4fdd-ac3e-9b79d0e622a0)

**Comment by VuDucVN** [comment]
Thanks, I'll check them out.

MB ***@***.***> 于 2024年3月22日周五 19:23写道：

**Comment by VuDucVN** [comment]
Hey my friends, as you say all the code is written encoded. Any
recommendations for the best tools or apps to do this efficiently ?


Vào Th 6, 22 thg 3, 2024 vào lúc 19:23 MB ***@***.***> đã
viết:

**Comment by VuDucVN** [comment]
And other things is that how can i find a text in the full code that have
been decoded ? That's like finding a needle in a haystack.

Vào Th 6, 22 thg 3, 2024 vào lúc 19:23 MB ***@***.***> đã
viết:

**Comment by Kiwironic** [comment]
Haha yes it's a bigger puzzle, that's why I always ask to have the pair in testing on. This way I can see the Chinese text and take a photo of it. Then encode it in Unicode and look for that in the app.

Cheers,
MB
________________________________

**Comment by VuDucVN** [comment]
This is all I can do, man. There are still a few lines in Chinese that
can't be found even if I search carefully in the code.

Vào 21:09, Th 6, 22 thg 3, 2024 MB ***@***.***> đã viết:

**Comment by Kiwironic** [comment]
I have been there, and you will find them if you follow the instructions I gave you. 

Use Notepad++, add project (the whole folder), then search in all project files, and translate. It will take a few days to get everything but at least you have the product to test it.

**Comment by VuDucVN** [comment]
Hey, you are genius, i can made it myself now. But I encountered this
problems below. The texts are too long and displays above other text. Can u
give me some suggestions to fix it, like reduce text side or margin it
somehow ?

Vào 0:10, CN, 24 thg 3, 2024 MB ***@***.***> đã viết:

**Comment by Kiwironic** [comment]
No way that I know of. You need to baht the text shorter.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by VuDucVN** [comment]
I've done all the translations. Do you want me to sent it for u so that u
can combine it with with your translated app ?

Vào 2:05, Th 6, 29 thg 3, 2024 MB ***@***.***> đã viết:

**Comment by Kiwironic** [comment]
There is no way we can combine them, it will break the app. It has to be done to all the  devices at once.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
